### ISSUE TITLE
Correct using of Future<Integer>  and ExecutorService

### ISSUE THREAD

**Issue by qnakovsky** [Ekaterina-Bogdanova/java_Array-list-value#2]
https://github.com/Ekaterina-Bogdanova/java_Array-list-value/blob/6b0c6c59f1767cf7a9efc66b8d56ff356a46ff00/ArrayListHandler.java#L27-L38

данный код работает, конечно, с многопоточностью, но приблизительно так: (для простоты аналогия из жизни): ты хочешь, чтобы тебе принесли яблок, банан и кофе 3 разных человека (вместо того, чтобы ходить самой), ты посылаешь первого за яблоком и ждешь, когда принесет, потом посылаешь второго за бананом и ждешь, пока принесет и затем только третьего.  

но могло быть  более эффективное по времени решение твоей просьбы: сказать СРАЗУ первому принеси яблок, второму сказать сразу принеси банан, а третьему сказать - неси кофе. а ЗАТЕМ, когда все отправлены, ты сидишь и ждешь, когда все они придут (ждешь резульат), кто-то раньше принесет, кто-то позже не важно. 

думаю, посыл понятен. сможешь поменять этот код так, что бы работал по более оптимальному сценарию? Пиши, если есть вопросы и хотела бы более наглядно увидеть, почему оно так работает

**Comment by rivka-sivka** [comment]
Нам нужен список задач ... попробую сейчас исправить
